//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticalAssignment.Models.DataEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbUnitTestingAssignmentEntities : DbContext
    {
        public DbUnitTestingAssignmentEntities()
            : base("name=DbUnitTestingAssignmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblStudent> tblStudents { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }

        public System.Data.Entity.DbSet<PracticalAssignment.Models.BusinessEntities.StudentVM> StudentVMs { get; set; }
    }
}
