//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticalAssignment.Models.DataEntities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblStudent
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Name is required!")]
        public string Name { get; set; }
        [Range(5, 100, ErrorMessage = "Age Must be between 5 to 100")]
        public Nullable<int> Age { get; set; }
        [Required(ErrorMessage = "Standard is required!")]
        public string Standard { get; set; }
    }
}
